### ISSUE TITLE
Error when comparing an item that extends another item.

### ISSUE THREAD

**Issue by TheColorRed** [angular/vscode-ng-language-service#1010]
When comparing two items, if one of the items extends another item an error is displayed even though they are of the same type.

As seen in the images below `MatStep` extends `CdkStep`, and `stepper.selected` is the type `CdkStep`. So there really shouldn't be an error in the comparison here.

**Note:** There are no build time or runtime errors.

![image](https://user-images.githubusercontent.com/1571806/101533746-d39cae00-395b-11eb-99bf-37690975d043.png)
![image](https://user-images.githubusercontent.com/1571806/101533683-bc5dc080-395b-11eb-81cb-0e4a2a367412.png)

![image](https://user-images.githubusercontent.com/1571806/101533806-eb743200-395b-11eb-9619-3a8281368066.png)
![image](https://user-images.githubusercontent.com/1571806/101533836-f62ec700-395b-11eb-8ddd-25891e96ea9a.png)

**Comment by kyliau** [comment]
This has been fixed by the new Ivy-native language service, released in [v11.1.0](https://github.com/angular/vscode-ng-language-service/releases/tag/v11.1.0).
It's an opt-in feature for now, please give it a try and let us know if you have any feedback.
Please make sure your project has [`strictTemplates`](https://angular.io/guide/angular-compiler-options#stricttemplates) enabled in `angularCompilerOptions`.

**Comment by TheColorRed** [comment]
@kyliau I have seemed to have lost the ability to <kbd>Ctrl+Click</kbd> on a template element and having it go to the component.

**Comment by kyliau** [comment]
@TheColorRed Could you please open a new issue? It's probably unrelated to this one.
Please check the logs. Also make sure you ran `ngcc` first.

**Comment by TheColorRed** [comment]
@kyliau yeah `ngcc` ran, I will open a new issue though. Thanks.
