### ISSUE TITLE
showing error for ng-dynamic-component npm package use

### ISSUE THREAD

**Issue by abhi-ezc** [angular/vscode-ng-language-service#1021]
Error showing when using ng-dynamic-component. Please fix this.

Can't bind to 'ndcDynamicInputs' since it isn't a known property of 'ndc-dynamic'.
1. If 'ndc-dynamic' is an Angular component and it has 'ndcDynamicInputs' input, then verify that it is part of this module.
2. If 'ndc-dynamic' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

**Comment by kyliau** [comment]
This has been fixed by the new Ivy-native language service, released in [v11.1.0](https://github.com/angular/vscode-ng-language-service/releases/tag/v11.1.0).
It's an opt-in feature for now, please give it a try and let us know if you have any feedback.
For the best editor experience, please make sure your project has [`strictTemplates`](https://angular.io/guide/angular-compiler-options#stricttemplates) enabled in `angularCompilerOptions`.
In case you run into similar bug, please file a new issue. I'll close this for now.
