### ISSUE TITLE
Angular Language Service and Emmet conflict mildly in component.html files

### ISSUE THREAD

**Issue by AndreThompson-Atlow** [angular/vscode-ng-language-service#1080]
If you open up any component.html file and use emmet to autocomplete a tag, say `<h2>` what you will get is

`<h2></h2>`

Now, if you want to use double brackets {{}} to put some kind of variable inside, Angular Language Service is supposed to automatically do the second set of brackets for you-- and in some cases it will. For example 

`<h2> {{}} </h2>`

That will autocomplete. However, if you start with emmet and make the first `<h2></h2>` and try to type the brackets inside, it will not autocomplete. You will end up with the following.

`<h2>{{</h2>`

This happens every single time you use emmet to complete tags for you and then try to instantly go into 'javascript land' in between them. 

To reproduce, just open up a component.html file and use emmet autocomplete. Try to use double brackets. 

Expected Behavior: It should autocomplete the brackets and recognize that you are now typing typescript code.

**Comment by atscott** [comment]
Hi @AndreThompson-Atlow, thanks for the report. After investigation, it seems to be an issue in vscode rather than the Angular extension. We don't provide any auto-closing behavior for the braces so there wouldn't be a conflict with the built in extensions there - you can test this out by disabling the Angular Language Service extension and you'll see the same issue. This is also the case for other auto-closes (try another `<h2>` and see that it also won't auto-close). 

It appears that when an extension provides auto-closing behavior for a language, it doesn't work if there's not whitespace on either side. Please file an issue in the vscode repository - I think that's where this issue should be addressed.
