### ISSUE TITLE
Ivy language service doesn't respect workspace settings

### ISSUE THREAD

**Issue by IamKayrox** [angular/vscode-ng-language-service#1108]
Ivy language service gets initialized when Ivy is disabled in the workspace settings

**To Reproduce**

1. Go to extension settings
2. Disable Experimental-ivy in Workspace settings
3. Enable Experimental-ivy in user settings

**Expected behavior**

Ivy language service not running

**Comment by essana3** [comment]
Same problem!

**Comment by atscott** [comment]
Hi, this happens because unchecking the box in VSCode removes the option from the `settings.json`. It's really confusing, but the effect of unchecking the box isn't an opt-out, but more specifically "not choosing to opting in". So the unset value in the workspace settings cannot override a set value in the user settings. In order to specifically disable the Ivy LS for a workspace when it's enabled in the user settings, you'll need to set `"angular.experiment-ivy"` to `false` in `settings.json`. 

In the future, we plan to be more careful of this checkbox interaction in the VSCode UI. For now, we're aiming to clarify this in #1115.
