### ISSUE TITLE
ivy-native issue - duplicated "Find all references" results

### ISSUE THREAD

**Issue by kunajs** [angular/vscode-ng-language-service#1124]
**Describe the bug**
After enabling the ivy-native feature, "Find all references" returns duplicated occurences of references (even with v11.2.1).

![image](https://user-images.githubusercontent.com/39991506/108166324-4fea0500-70f4-11eb-9f4e-6e5f1cf04af2.png)

![image](https://user-images.githubusercontent.com/39991506/108166072-ecf86e00-70f3-11eb-89ee-1c961e366529.png)

With unchecked "Experimental-Ivy" feature it works fine.

Seems to be somehow related to this issue: https://github.com/angular/vscode-ng-language-service/issues/1109

**Comment by ivanwonder** [comment]
I think it's not related to that issue. my guess is that one result comes from vscode ts server, another comes from Angular LS.

**Comment by atscott** [comment]
@kunajs - What version of the extension are you using? v11.2.1 is known to have problems.

**Comment by atscott** [comment]
@kunajs My mistake, I didn't realize there was another release. Do you have a project that you can share so we can reproduce the issue? I have not been able to reproduce this locally.

**Comment by atscott** [comment]
@kunajs - I am able to reproduce this locally now. It appears VSCode may have a different internal implementation of "find all references" and "go to references". It was assumed that VSCode de-duplicated these results in both places but they may only be doing that for their `gotoSymbol`:

https://github.com/microsoft/vscode/blob/ea4d99921cc790d49194e897021faee02a1847f7/src/vs/editor/contrib/gotoSymbol/referencesModel.ts#L144-L174
https://github.com/microsoft/vscode/blob/ea4d99921cc790d49194e897021faee02a1847f7/src/vs/editor/contrib/gotoSymbol/referencesModel.ts#L283-L285

We can add a workaround on our end for this. I expect that this should also be considered an issue on the VSCode side that should be fixed there as well.

**Comment by atscott** [comment]
The "Find all references" command is provided by the [Reference Search View](https://marketplace.visualstudio.com/items?itemName=ms-vscode.references-view) extension. It doesn't appear as though they have the same de-duplication logic there:https://github.com/microsoft/vscode-references-view/blob/f1b526b39c97981c81d52a98d6e66f8f699dc38a/src/references/model.ts#L63-L74
I'll see about submitting an issue and determining if this can be fixed in that extension rather than a workaround here. That would be the desired solution. Our extension provides valid references. It should be the responsibility of the editor / the "Reference Search View" extension to de-duplicate results from the various extensions which provide them.

**Comment by atscott** [comment]
PR to fix in the extension: https://github.com/microsoft/vscode-references-view/pull/66
Issue in vscode repo: https://github.com/microsoft/vscode/issues/117095
