### ISSUE TITLE
ngTemplateContextGuard infers incorrect type when using AsyncPipe and strict equality

### ISSUE THREAD

**Issue by snebjorn** [angular/vscode-ng-language-service#1137]
**Describe the bug**

Given that `isLoading$: Observable<boolean>`.
Then `isLoading` in the below html is inferred as type `false | true | null`.

```html
<ng-container *ngxAlias="(isLoading$ | async) === true as isLoading"></ng-container>
```
![image](https://user-images.githubusercontent.com/1266245/108492982-12c57480-72a6-11eb-854f-e4084b023923.png)

But it can never be `null`. As it's comparing `boolean | undefined | null` from the AsyncPipe to `=== true`. This assures the type is not `null`.

![image](https://user-images.githubusercontent.com/1266245/108503613-f8df5e00-72b4-11eb-943b-11046212eb18.png)

-----

[ngxAlias](https://github.com/TNG/ngx-structurals/blob/master/projects/ngx-structurals/src/lib/ngx-alias/ngx-alias.directive.ts#L39) uses `ngTemplateContextGuard`
```ts
public static ngTemplateContextGuard<T>(dir: NgxAliasDirective<T>, ctx: unknown): ctx is NgxAliasContext<T> {
  return true;
}
```
So I don't think the error is with `ngxAlias`

**To Reproduce**

1. npm install @tngtech/ngx-structurals 
2. Define `isLoading$: Observable<boolean>` in your component
3. Add `*ngxAlias="(isLoading$ | async) === true as isLoading"` in the html
4. See incorrect type error

**Expected behavior**

The reported type of `isLoading` should be `false | true` or `boolean`

**Additional context**

> Angular Language Service Version: 11.2.2 (experimental ivy enabled)
> 
> VSCode:
> Version: 1.53.2 (user setup)
> Electron: 11.2.1
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.19041

**Comment by atscott** [comment]
This is an issue with the `ngxAlias` directive. The language service is showing what the compiler already sees. Quick tip: You can right click in your template and select "View Template Type Check Block" to see the code that's generated to typecheck the template file.

> To provide a more specific type for an input expression to a directive within the template, add a `ngTemplateGuard_xx` property to the directive, where the suffix to the static property name is the @Input field name

https://angular.io/guide/structural-directives#make-in-template-type-requirements-more-specific-with-template-guards

Even with that, I'm not sure it's possible to narrow the type to just `true` here. There's no way to write a narrowing function to narrow it to `true` when it can actually be something else.

Notice that the `ngTemplateContextGuard` for `ngIf` uses `Exclude<T, false|0|''|null|undefined>` because the body of `ngIf` is only present when the input is `truthy`. Without that, we couldn't narrow the type of `ngIf` any further either.

**Comment by Airblader** [comment]
@atscott 

The type of the directive is shown as `declare (property) NgxAliasDirective<boolean>.ngxAlias: boolean`, but the type of the variable is still shown as `boolean | null`. I'm sorry if I'm missing something, but how can that be explained? It seems that this is indeed a language service issue to me?

**Comment by Airblader** [comment]
> Even with that, I'm not sure it's possible to narrow the type to just true here.

Note that this isn't the goal. The expected type is `boolean`, since `false` is of course a valid value. The problem is rather that the actual type is `boolean | null` when the type in the template context already (correctly) is just `boolean`, so the language service seems to add a `| null` somewhere.

**Comment by atscott** [comment]
@Airblader - the `NgxAliasContext` `ngxAlias` and `$implicit` both have types of `T|null`. https://github.com/TNG/ngx-structurals/blob/master/projects/ngx-structurals/src/lib/ngx-alias/ngx-alias.directive.ts#L16-L23
In contrast, `ngIf` cheats a little and uses `$impliciit: T = null!`

**Comment by Airblader** [comment]
d'oh. Thanks for pointing it out, that was a big blind spot.
