### ISSUE TITLE
Filter diagnostics of certain error codes

### ISSUE THREAD

**Issue by kevinmallinsonflynn** [angular/vscode-ng-language-service#1243]
In our project, we use `require` to load all components. This works, and the app runs fine.

Our app uses string interpolation for some reason - however it is valid code and does compile properly. As a result, we shouldn't receive this error. We also receive this error if we remove the string interpolation.

Here is an example:

```
@Component({
    selector: 'project-review-dialog',
    styles: [`${require('./project-review-dialog.component.css')}`],
    template: `${require('./project-review-dialog.component.html')}`
})
```

Thus, we get this error:

![image](https://user-images.githubusercontent.com/73043930/113214883-173b6080-9248-11eb-808c-465313263304.png)

---

Note: I have seen the other tickets that have this issue. All of them provided no solution.

I am hoping you might have a solution for this (without forcing us to change any code)

Thanks.

**Comment by kevinmallinsonflynn** [comment]
@kyliau No, I'm not.

I have enabled it, and now get a different error:

![image](https://user-images.githubusercontent.com/73043930/113301447-041ea400-92cd-11eb-9f83-6b2339eee0ac.png)

**Comment by kyliau** [comment]
@kevinmallinsonflynn Thanks for checking both View Engine and Ivy implementation.
This is expected, because it is almost impossible for the compiler to statically analyze the expression **at build time**. For example, users could concatenate multiple strings, call functions, etc to form the template url. 
It also makes source mapping incredibly hard. Source mapping is used by the compiler to highlight errors in user's code.
That said, is there any reason `templateUrl` can't be used?
Looking at your example, it seems perfectly valid to write
```ts
@Component({
  templateUrl: './timeline-event-card.component.html',
})
```
This is the recommended and well supported approach, and is tested extensively in the language service.

**Comment by kevinmallinsonflynn** [comment]
@kyliau I am new to this app, but i've been told it was done this way to facilitate the migration from AngularJS to Angular2+
We are currently running a hybrid app with mixed components from AngularJS and 2+.

I understand this is non-standard how we are currently specifying `template` - in that case, is there any way there could be a setting which would allow us to disable this rule?

**Comment by ikemtz** [comment]
I'm in a similar boat, I have a collection of base/abstract component classes that now require angular attributes (component/directive, etc.).  Code compiles fine, but the error messages can be a PITA.  Similar to other project types, there's should be a way of disabling specific warning/error condition codes.  Something similar to this:

```
  "angular.log": "verbose",
  "angular.ignoreErrorCodes": "-99934;ab123;-888",
```
