### ISSUE TITLE
Disable ngcc background compilation

### ISSUE THREAD

**Issue by glebmachine** [angular/vscode-ng-language-service#1251]
**Is your feature request related to a problem? Please describe.**
One of my project is at angular 8, and every time i start my vscode language service started ngcc and compile all dependencies
I would like to disable this feature. For now i should uninstall language service : /

**Describe the solution you'd like**
add configuration `enableBackgroundIvyCompilation` flag

**Comment by kyliau** [comment]
Hi @glebmachine, thanks for the suggestion. Ivy language service requires the `.d.ts` files produced by ngcc to function properly. In your situation, would you rather run ngcc yourself prior to launching vscode?
We can definitely provide such flag, but it'll put the burden on users to run ngcc whenever a dependency is changed. Otherwise, it'll lead to unexpected errors. I'd consider this an "expert" mode for users who understand the risks.

**Comment by glebmachine** [comment]
So what angular 8 users should do?
It broke dependencies after compilation, and i should disable it to work with angular < 9 projects (without language service at all)

May plugin check angular version first, before compilation?

**Comment by kdaniel21** [comment]
I'm having the same problem and right after starting VSCode (and Angular Language Features start to run) my Angular 8 project immediately breaks with the following error message. (I'm adding it so that others might be able to find this issue easier).
`Uncaught TypeError: can't access property "id", ngModuleType.ngModuleDef is undefined`

Would something like rollbacking to a previous version of the extension help?

**Comment by kyliau** [comment]
@glebmachine @kdaniel21 Could you help me understand your project setup, please? This is what I gathered so far:
1. You are using Ivy language service
2. Your project is presumably using View Engine
3. Where did you see the error? Could you please copy and paste the entire error message?
4. When you say "ngcc broke dependencies after compilation", what does that mean? In what way are your dependencies broken? The app no longer compiles?
5. Do you know exactly which dependencies are broken? Could you please list them here?

From my side, I tried the extension in a newly created version 8 project, but did not run into the issues above, so there must be additional dependencies / configuration that are causing problems.

**Comment by Agoni1** [comment]
@kyliau I had the same problem. I have an old Angular8 project that worked fine before. But now when I open it with VSCode, I get the above error.

**Comment by kyliau** [comment]
@Agoni1 We've determined that the new Ivy language service cannot support Angular version 8 and below. This is because the `ngcc` support is incomplete in version 8.
Since version 8 is no longer under [LTS support](https://angular.io/guide/releases#support-policy-and-schedule), we will fix the extension to automatically fallback to View Engine language service.

**Comment by n9niwas** [comment]
I would also like to see a setting that disables ngcc or doesn't run it again if it was already executed externally.

Our packages rarely change and ngcc is executed as part of `ng serve` anyways.

Besides, we currently experience an issue with how it's executed from extension.
Ngcc is failing on a particular package via command `ngcc --tsconfig <tsconfig>`  but is working fine from `ng serve` or `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`.

Thus in actual code there are no issues, but extension is producing these annoying messages:

<img width="360" alt="Screen Shot 2021-04-21 at 2 51 50 AM" src="https://user-images.githubusercontent.com/9402214/115509533-8e16b880-a24c-11eb-852a-ab9deb230d60.png">
