### ISSUE TITLE
Ivy mode ends up breaking 3rd party bundler somehow, modifies libraries in node_modules?

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#1421]
When using the ivy library, my project ends up breaking in a funny way. When doing a npm ci in my angular project, things seem to return to normal (for a few reloads). What's going on here???

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ShaneK** [comment]
I think I've experienced this same issue. Using an older version of ag-grid (21.1.0), the vs code angular language service would modify something in node modules and break my build. This doesn't happen, for example, if I use webstorm instead of vs code. It also doesn't happen on newer versions of ag-grid (23.0.2 doesn't have this issue). However, it's very odd that this is a problem at all. Ideally, the angular language service extension wouldn't be modifying anything in node_modules (this issue also doesn't occur if you disable this extension).

So I do think this is a bug with this extension @atscott

**Comment by atscott** [comment]
@jpike88 Your submission does not fall into the category of a bug report but rather a support ticket. It does not contain actionable information or an apt description of a problem.

@ShaneK Thank you for the additional context. This sounds like a possible issue with [ngcc](https://github.com/angular/angular/blob/master/packages/compiler/design/architecture.md#high-level-proposal), which is required to run and gather metadata from libraries for the language service. It adds some lock files to various places while running but I don't know the specifics of your build or what exactly broke. 

Please do submit a new issue if you encounter this again with a reproduction, steps to reproduce, or a snapshot of your project when it becomes broken (shared privately if needed).

**Comment by jpike88** [comment]
@ShaneK will you do the minimal repro and cc me in? Or want me to try

**Comment by ShaneK** [comment]
@jpike88 I seem to be having a hard time creating a minimal reproduction. If you're able to consistently, feel free!

**Comment by jpike88** [comment]
Ehh screw it, if you can't then I doubt I can, it has the same random behaviour as yours. The day they disable the ability to use the old View Engine and we're forced to use this ngcc I'll make a scene. I'd imagine a lot of ppl like us are out there but haven't decided to turn it back on since.
