### ISSUE TITLE
Nested ngFor lose object type

### ISSUE THREAD

**Issue by badre429** [angular/vscode-ng-language-service#144]
```html
<ng-template ngFor let-group [ngForOf]="Groups">      
      <ng-template ngFor let-user [ngForOf]="group.Users">
           {{user.name}}
      </ng-template>
</ng-template>
```
***{{user.}}***   down't get the intellisense because user is of type any

**Comment by kyliau** [comment]
This is due to way template variable declarations are determined.
https://github.com/angular/angular/blob/8912b11f56b9d1ca2a67317ca05005e5b8a6dae3/packages/compiler-cli/src/diagnostics/expression_diagnostics.ts#L93
First, we should traverse AST path from HEAD, then make available any variables that are in scope as we traverse the path. Would be happy to review a PR for this!
