### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by inhumanxd** [angular/vscode-ng-language-service#1464]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `12.0.5`
- OS Version: `Linux x64 5.8.0-59-generic`
- VS Code version: `1.59.0-insider`

[Angular.ng-template-unresponsive.cpuprofile.txt](https://github.com/angular/vscode-ng-language-service/files/6897922/Angular.ng-template-unresponsive.cpuprofile.txt)

**Comment by atscott** [comment]
The provided profile is only 5 seconds during the initial compilation. We would expect high CPU load while compiling the application.

If the issue is persistent, please submit a new issue and provide a more complete CPU profile with more information about your project size and setup. In addition, the log file gives us insight into the behavior and performance of the extension. Follow the directions on the bug submission template to enable verbose logs and include the logs in the report.
