### ISSUE TITLE
Code completion intermittently swallows character after

### ISSUE THREAD

**Issue by ardunster** [angular/vscode-ng-language-service#1503]
I looked for similar issues and didn't see anything close.

# 🐞 bug report

### Is this a regression?

Unknown, I just started using Angular Language Server.

### Description

Sometimes when working on a template file, if I use a code completion option, the character after my cursor will also get replaced. It does not happen consistently for specific pieces of code, it seems more like it happens when I am working quickly. Most frequently it will happen when I copy and paste a piece of template, and then start double clicking on variable names to change them. Example:

Here, I have pasted several lines of code, and double clicked the `dischargeDate` property:
![nglanguageservice1](https://user-images.githubusercontent.com/61255483/132424885-d27d050b-aee8-43c2-be40-c2353b3151d4.png)

I start typing what I want to replace it:
![nglanguageservice2](https://user-images.githubusercontent.com/61255483/132424914-ae9646e6-3467-4cc3-b42a-937ac6905376.png)

Then I hit enter with the correct option highlighted, and get this:
![nglanguageservice3](https://user-images.githubusercontent.com/61255483/132424966-3459f4bb-c25e-4648-b6ce-4caedf182d9c.png)

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [?] Angular Language Service server

## Reproduction

It may take several tries as sometimes the same piece of code and the same inputs behave as expected and sometimes they don't. (I had to retry several times to get the screenshot progression for example.) 
1. Copy and paste a piece of an angular template html file.
2. Double click a variable property name that is enclosed in double quotes that you would like to change (associated with the component that uses the template).
3. Start typing a valid replacement, and hit "enter" with the chosen replacement selected.
4. Closing double quote has been replaced when code completion appears.

I had it happen once or twice with closing `>` characters too but it seems less frequent, or maybe I am just not double clicking and changing things as often in that case.

**Expected behavior**

Code completion should not delete the closing syntax of whatever code block I am in when entering a completion.

### **Logs**

I did not take a log file as this code is not publicly sharable and the log file could contain code. If necessary I may be able to privately disclose a log file. 

### **Screenshots**

See above.

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 12.2.1
Node: 14.16.0
Package Manager: npm 7.20.6
OS: win32 x64

Angular: 12.2.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.1
@angular-devkit/build-angular   12.2.1
@angular-devkit/core            12.2.1
@angular-devkit/schematics      12.2.1
@schematics/angular             12.2.1
ng-packagr                      12.2.0
rxjs                            6.6.7
typescript                      4.3.5
webpack                         5.50.0

</code></pre>

Extension Version:
<pre><code>
v12.2.0

</code></pre>

VSCode Version:
<pre><code>
Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

</code></pre>

Operating System:
<pre><code>
Windows 10 Enterprise
Version 1909
OS build 18363.1734

</code></pre>

**Anything else relevant?**
Not that I am aware of.

**Comment by atscott** [comment]
I wasn't able to reproduce this issue when Angular was providing the completion results. I see that in your example, the completion icons before all the completion items are the "abc" ones, which means those are just completions found from words in the document. 

Does this ever happen when the completions are not the word completions from the document? I realize this is a frustrating DX, but I don't think there's really much we can do since those aren't completions that we control.

**Comment by ardunster** [comment]
That's weird, in the two screenshots I have they have the abc, but in testing again this morning they all have a wrench icon, unless I disable the extension. Although come to think of it I may never have reloaded the window after enabling the extension yesterday (since I had it installed originally before I realized the code I was working with originally was AngularJS, not Angular). I'll keep an eye on that icon and see if it happens again now that I have reloaded VSCode.

**Comment by ardunster** [comment]
Can verify it happens with the wrench icon also, just happened to me as I was looking at it. Possibly relevant that it was a new property for that object that I had not previously used in that document.

**Comment by ardunster** [comment]
Log file doesn't seem to have anything besides path names, so here it is. 
I turned logging on with the accompanying language server restart, then started working again. The last thing that happened in the log file was a completion that deleted a closing quote. Didn't notice whether it was `abc` or wrench icon, but again, I _never_ had this problem before enabling the language server.
Is it normal for it to reload and log data as if `tsconfig.json` has changed when it hasn't?  I noticed it did that about 15 minutes prior to this (on a different log file).
It complains about the `temp.html` file not having a project, but that's a file I'm working on rewriting from an absolute spaghetti mess of AngularJS to live in the Angular app now. it's just convenient to have it in the same directory while I am working; no code references it anywhere.

[angularlanguageserver.log](https://github.com/angular/vscode-ng-language-service/files/7131088/angularlanguageserver.log)

**Comment by atscott** [comment]
I'm unfortunately at a loss as to why the vscode completion chooses to replace a range beyond the word. It appears to have something to do with the interaction of our mirroring the content of a document using change events https://github.com/angular/vscode-ng-language-service/blob/81b8fabc308fec839603a6198c1b994d4bd73aeb/server/src/session.ts#L751-L771 but the strategy there seems to match what is documented. 

Disabling the content sync code there does make the problem go away, but we definitely can't remove that because everything relies on that part.

I'm able to consistently reproduce this by _very quickly_:
1. Taking `(input)="setQuery($any($event.target).value)"`
2. `value` with ctrl+backspace
3. typing `val`
4. hitting the `tab` key
We apply the correct change based on the replacement
![image](https://user-images.githubusercontent.com/479713/132596251-dcc0a8c6-1b52-48a8-a367-6dede3ae7c2d.png)
When the text is `(input)="setQuery($any($event.target).va)l"`, the next change event has a `rangeLength` of `4` which is odd because it should be `3`. This seems to indicate that whatever completion item was being used had the wrong replacement range, but I don't know where that completion is coming from.

**Comment by ardunster** [comment]
Thanks for checking into it.  I dug into the `.ts` file you linked a little but it's not immediately obvious to me where the parameters are coming from and I'm not familiar with the overall shape of the project.   I guess for the moment I'll try to type slower ;)

**Comment by atscott** [comment]
I found today that disabling the built in "HTML Language Features" extension also seems to resolve the issue.

**Comment by atscott** [comment]
Filed an issue on the vscode repo: https://github.com/microsoft/vscode/issues/132785

**Comment by ardunster** [comment]
Awesome, I will follow that issue. Thanks so much for tracking that down!
