### ISSUE TITLE
Legacy View Engine not working in v13 project

### ISSUE THREAD

**Issue by kyroluskamal** [angular/vscode-ng-language-service#1556]
### Description
Simply the errors shown in the images are caused by the extension, and disappeared when I disabled the extension
https://ibb.co/mGtV8zM
https://ibb.co/pvYF48x
https://ibb.co/1L7D1NL

## Bug Type
What does this bug affect
- [x] Angular Language Service VSCode extension

## Reproduction

1. Create new angular app
2. use router-outlet or  Add Angular material and use any angular material component or use ngIf, nsSwitch for eaxmple

I tried use it with visual studio 2019, it doesn't show errors but it doesn't work too.

**Comment by atscott** [comment]
I was not able to reproduce this. I created a fresh project with the CLI and routing. `router-outlet` was recognized as a directive.

I'm not sure what exactly the steps are trying to indicate. Are you trying to use the `router-outlet` without importing the `RouterModule`? Are you trying to use material and things from `@angular/common` without importing those modules? Do you have an example project? Presumably, if those are really your only 2 steps, you should be able to provide this as a github repo since there's nothing private about a new empty project.

**Comment by kyroluskamal** [comment]
I imported `RouterModule`, `CommonModule`, and all required material modules. 
First, I thought that there is something wrong happened after updating to angular 13, so, I decided to create a new Angular app to see the differences. I found the error at router-outlet shown this image https://ibb.co/mGtV8zM in the new app. So, I thought that may be the Angular extension. I disabled it then the errors were gone from the new project and from my project.

You don't need any repro, Just use `ng new <app-name>` to create a new app, and use router-outlet or ngIf or angular material and you will see the errors.

I created a video for you to show what happens and how the errors are shown
https://drive.google.com/file/d/1U6-iPY63rBk2dfI5qWEl7T18SEeLul7Y/view?usp=sharing

Then, I enabled it again, and of course, the errors are shown again, but this time I decided to run the project. It worked correctly while the errors are shown. 

Then, I thought that maybe the errors are shown in VS code only, so, I used visual studio 2019 and installed the extension on it. It didn't show any errors but it did not work too.

**Comment by atscott** [comment]
I do believe you when you're saying you have errors. But there's just too much missing here for me to determine _why_. As I mentioned in the previous comment, I was not able to reproduce this using `ng new <app name>`. I do not get the errors. You removed a lot of the issue template when you submitted this issue. Please provide the following information:

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>
If the issue is accompanied by log file output, please share it below.

Set the Angular Log level to verbose by opening settings (File/Preferences/Settings on Windows, Code/Preferences/Settings on Mac), go to Extensions/Angular Language Service, set `angular.log` to `verbose`.

To open the log file, go to the command palette (Cmd+Shift+P on Mac, Ctrl+Shift+P on Windows), search `Open Angular Server log`.
</code></pre>

Alternatively, if the log file is long, it can be uploaded instead of pasting below. 
## 🌍  Your Environment
**Angular Version:**
<pre><code>
 run `ng version` and paste output below 


</code></pre>

Extension Version:
<pre><code>
 Enter the version of 'Angular Language Service'. Example: v11.2.11


</code></pre>

VSCode Version:
<pre><code>
 Open 'About Visual Studio Code' and paste output below 


</code></pre>

Operating System:
<pre><code>
 Example: Windows 10 Version 1703 OS Build 15063.483  


</code></pre>

In addition, because I cannot reproduce this issue based on the steps you've outlined, please provide a project repository that I can clone.

**Comment by kyroluskamal** [comment]
**Logs**
https://drive.google.com/file/d/1iuLx4yEzVerHMlIs6BqO3Z7XZRyu3g6S/view?usp=sharing

**Angular Version**
Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1300.1
@angular-devkit/core         13.0.1
@angular-devkit/schematics   13.0.1
@schematics/angular          13.0.1

**VSCode Version:**
Version: 1.62.0 (user setup)
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:23:01.379Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Operating System:
Windows 10 Home single language   Version: 10.0.19043 build 19043

**Comment by kyroluskamal** [comment]
I want to add that these errors appear only after updating to angular 13. Also, I disabled all other extensions on VS code but the error is still there

**Comment by atscott** [comment]
@kyroluskamal can you check your extension options and let me know if the have the “legacy view engine” checkbox checked? It so, please uncheck it and see if that resolves the issue.

**Comment by kyroluskamal** [comment]
Yes, it works now.  I was sad because I thought that I can't use this wonderful extension. Actually, you save me now. Thank you very much
