### ISSUE TITLE
Ngcc running conflicts with other tasks in the workspace

### ISSUE THREAD

**Issue by DanWebb** [angular/vscode-ng-language-service#1570]
# 🐞 bug report

### Is this a regression?

Yes, I've been using the extension for about a year and never had problems previously.

### Description

When the Angular Language Service extension is running it seems to prevent other ngcc tasks from running.

It causes an overwrite of the `__ngcc_lock_file__` in `/@angular/compiler-cli/ngcc`

In this specific case, I'm unable to run [Angular Storybook](https://storybook.js.org/docs/angular/get-started/introduction) whilst the Angular Language Service is also running, to fix this the extension has to be disabled and the `__ngcc_lock_file__` deleted before Storybook will run again.

## Bug Type

- [x] Other running ngcc processes

## Reproduction

1. Install the extension
2. Run another ngcc process from the same workspace/node_modules folder

**Expected behavior**

Angular Language Server should be self contained, it's running processes shouldn't affect other 

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>
[1] ERR! Error: ngcc is already running at process with id 85831.
[1] ERR! (If you are sure no ngcc process is running then you should delete the lock-file at .../node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
</code></pre>

## 🌍  Your Environment

- **Angular Version:** 10
- Extension Version: latest
- VSCode Version: 1.62.2
- Operating System: MacOS Big Sur 11.4

**Comment by atscott** [comment]
@DanWebb Could you be a bit more specific? The `__ngcc_lock_file__` is an artifact of `ngcc` itself. The Language Service must run `ngcc` to ensure library metdata is present to work correctly. This isn't something we can change any time in the near future.

The lock file should go away when the process completes. Are you saying that two `ngcc` processes conflict with each other? This doesn't seem to be the case based on the logs, which are indicating that the lock file was detected and it's waiting for that to go away.

I'm not familiar with the implementation details of storybook either. Presumably, it's also blocked by an existing `ngcc` process (seems to be the case: https://github.com/storybookjs/storybook/blob/23f798da33cdb77f0b83be9a440334641da4745e/app/angular/src/server/framework-preset-angular-ivy.ts). 

It doesn't appear that the language service is the problem here. You have several processes that need to run `ngcc`, each should wait for the other to complete, run their own, and then everything should continue merrily along. The issue may be with `ngcc` instead if there's a situation that's not being handled correctly here.

**Comment by DanWebb** [comment]
@atscott Storybook doesn't wait for the lock file to go away, it fails with an error immediately. Am I understanding correctly that you're suggesting that Storybook should instead wait for the ngcc process from Angular Language Service to complete?

Would it be possible for Angular Language Service to not use the version of Angular installed inside the current projects node_modules to avoid the conflict?

I was quite surprised to find the issue was due to the extension running at the same time, I wouldn't expect for an extension in my code editor to be holding up running the actual project. It's a large codebase so I suspect the conflict is more noticeable because the ngcc process from the extension is taking a while.

**Comment by atscott** [comment]
> @atscott Storybook doesn't wait for the lock file to go away, it fails with an error immediately. Am I understanding correctly that you're suggesting that Storybook should instead wait for the ngcc process from Angular Language Service to complete?

Again, I'm not familiar enough to comment. Though the waiting is a property of `ngcc` itself. The language service extension doesn't look for the lock file - it just launches a new `ngcc` process and waits for it to complete (or fail). 


Side note:  I see that you are on `1.62.2`, where [this](https://github.com/microsoft/vscode/issues/136988) issue still exists (also tracked in https://github.com/angular/vscode-ng-language-service/issues/1565).

> Would it be possible for Angular Language Service to not use the version of Angular installed inside the current projects node_modules to avoid the conflict?

This actually would cause _more_ of a conflict. If we use a different version of `ngcc` in the language service, it would clobber the `ngcc` output of the other version from `node_modules` and the two versions would continue to compete in producing metadata outputs that they can read.

> I was quite surprised to find the issue was due to the extension running at the same time, I wouldn't expect for an extension in my code editor to be holding up running the actual project. It's a large codebase so I suspect the conflict is more noticeable because the ngcc process from the extension is taking a while.

It's less than ideal, but it's again something we have to do. `ngcc` needs to be run for compiling/running your application as well as something that storybook likely needs. Once it has been run, the process is generally a no-op and would complete instantly so there shouldn't be _additional_ wait time in that respect.

**Comment by DanWebb** [comment]
Thanks for explaining.

> Once it has been run, the process is generally a no-op and would complete instantly so there shouldn't be additional wait time in that respect.

When does the extension need to run `ngcc`? It's noticeable after an `npm install`

Sorry that this is slightly off topic, but if all else fails, is there a way to stop the extension running `ngcc` and just keep the extension for Angular syntax highlighting?

**Comment by atscott** [comment]
> When does the extension need to run `ngcc`? It's noticeable after an `npm install`

Yea, this is exactly when it would need to run. From the `ngcc` [readme](https://github.com/angular/angular/tree/master/packages/compiler-cli/ngcc):

> This compiler will convert node_modules compiled with ngc, into node_modules which appear to have been compiled with ngtsc.
> This conversion will allow such "legacy" packages to be used by the Ivy rendering engine.

That is, libraries which were published with the legacy "View Engine" metadata need to be run through `ngcc` to be compatible for interpretation in Ivy. 

> Sorry that this is slightly off topic, but if all else fails, is there a way to stop the extension running `ngcc` and just keep the extension for Angular syntax highlighting?

Not currently, though we could consider an extension option to disable `ngcc`. This is somewhat scary because `ngcc` does need to run in most cases. If it doesn't, you'll start seeing a bunch of errors because library components can't be interpreted. If we added this option, we would likely want to accompany it with a reminder notification on start-up so devs don't forget that could be the likely cause of errors they might see.

Side note: If you really do mean just syntax highlighting, you can enable the "legacy view engine" option which doesn't run `ngcc`. This option is only really intended to be used for older projects that aren't compatible with Ivy though. We don't intend to ensure it works well (with respect to the information it presents) for v13+ projects. The syntax highlighting grammars are shared between the VE and Ivy options though so that would at least work.

**Comment by DanWebb** [comment]
Thanks @atscott that's really helpful to know and hopefully helpful for others who might come here facing the same issue in the future. I think it covers all my concerns, happy to close!
