### ISSUE TITLE
Renaming @Input properties across all usages

### ISSUE THREAD

**Issue by Exac** [angular/vscode-ng-language-service#1853]
**Is your feature request related to a problem? Please describe.**
Someone on Reddit was complaining that Angular does not have a way to make `@Input`s required. I responded to his post and gave the following example:
```typescript
@Component({
  selector: 'example[requiredInput]',
  template: `<h1>Required input is {{requiredInput}}!</h1>`,
})
export class ExampleComponent {
  @Input() requiredInput: string;
}
```
```typescript
<example requiredInput="foo"/>
```
His response was
> But how would you rename the variable? Cant right click > Rename symbol. What if there’s 10 of these inputs?

There are two options in the existing right-click menu on StackBlitz, "Rename symbol" and "Change All Occurrences". Change All Occurrences works in the `example.component.ts`, but will not rename the property in the parent component's template.

Is the correct response to just cite the Open-Closed Principle?

# 🚀 feature request

### Description
It would be great to be able to rename `@Input` properties easily, and have the change propagate across all usages.

If there is a better place to open this feature request, please let me know.

### Feature Type
What does this bug affect

- [ ] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### Describe the solution you'd like
Open to suggestions. My initial assumption/expectation was that "Change All Occurrences" would do this.

### Describe alternatives you've considered
"Rename symbol" and "Change All Occurrences" do not rename the `@Input`s in any usages.

### Anything else relevant?

[StackBlitz](https://stackblitz.com/edit/angular-ivy-yozggx?file=src/app/example.component.ts)
[Reddit thread](https://www.reddit.com/r/Angular2/comments/10fbnt1/comment/j50cm9f/?context=3)

**Comment by atscott** [comment]
Required inputs will be coming soon so any other workarounds aren't really necessary. 

Secondly, renaming inputs that aren't aliased is already possible from templates, though it wouldn't include the selector in the renaming. It isn't possible from outside template strings or template files due to https://github.com/microsoft/vscode/issues/115354. All we can do is ask you to upvote that issue if you'd like renaming from TS files since it's a limitation of VSCode.

Closing as done/not possible in VSCode/solved by actually implementing required inputs.
