### ISSUE TITLE
how to debug this project in vscode?

### ISSUE THREAD

**Issue by ahpudabai** [angular/vscode-ng-language-service#1867]
after I set `debugger` in source code, it break in this file:  "/private/var/tmp/_bazel_zhouguofeng/5d6b93aff1f51fe69699566840d3b3a8/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/client/src/client.js", how can I set breakpoint in ts source code?

**Comment by atscott** [comment]
This is the expected behavior. This project is now built with `bazel`. `ts_project` from `rules_js` compiles entirely in the output tree. Source files are copied into bazel directories as part of the build. You can set breakpoints in the source files within bazel-bin to debug or by adding `debugger` statements to the code before compilation.
