### ISSUE TITLE
Output console randomly opens to ALS log

### ISSUE THREAD

**Issue by mpicard** [angular/vscode-ng-language-service#187]
ALS often opens the "Output" console log in VSCode with debugging statements when writing Angular code. I'd expect that output not to open ever. I've disabled all plugins except ALS and it seems to be the culprit. I noticed that it often happens when an error occurs in the syntax in typescript or html files. 

Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:57:00.652Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Ubuntu 16.04

**Comment by MarkSheinkman** [comment]
Yup. Super annoying. Writing to the console without activating it, like other modules do, would be much better.

**Comment by shhdgit** [comment]
Same to me, that's very annoying.

**Comment by SamoB25** [comment]
Super annoying

**Comment by danwulff** [comment]
This is killing me. It likely has something to do with an "OutputChannel" if anyone has time to look at the source code of this extension: https://code.visualstudio.com/docs/extensionAPI/vscode-api#OutputChannel

**Comment by trumbitta** [comment]
@danwulff https://github.com/angular/vscode-ng-language-service/blob/master/server/src/server.ts#L171 ?

**Comment by chuckjaz** [comment]
Given the response in https://github.com/Microsoft/vscode/issues/36844#issuecomment-340404587 the client should be setting `revealOutputChannelOn` to off.

**Comment by willwsharp** [comment]
@chuckjaz Is setting the `revealOutputChannelOn` to off something that can be changed via configuration  by the user?

**Comment by snewell92** [comment]
The option is a part of `LanguageClientOptions` which is passed to the constructor of a `LanguageClient` - I can make a quick PR.

**Comment by danwulff** [comment]
@snewell92 Thanks for putting up a PR! I didn't have time to look into it further.

**Comment by snewell92** [comment]
I referenced several other open related issues just now too. Another PR could easily be made such that instead of `RevealOutputChannelOn.Never`, that property is set to a configurable field (which would close issue 131).

And now we wait patiently 😸

**Comment by wbhob** [comment]
Yeah, can we get this merged please? This extension is great except for this one awful bug that I reported months ago and got marked as resolved when it really wasn't.

**Comment by dottodot** [comment]
In the latest versions of cli and angular this is now almost unuseable. I barely have enough time to read the terminal messages before it switches to the output tab.

**Comment by Martinspire** [comment]
I get that changing a value by the user is a possibility, but why is it opening in the first place? It seems to me that this is only needed for people debugging the Angular Language Service, not somebody working on Angular.

I also get them. In multiple projects. Most of the time after changing code to something I know is wrong, but I need to do that in order to continue on my code (I tend to copy code from some place to a new place because I need some variables or object to be the same). I'm not even saving it and it seems to freak out.

When I open Word, Notepad or whatever, it also doesn't randomly popup a debugger output because a plugin or extension is failing. Even if VS Code has some setting to display stuff, I still think it should be handled differently because in other languages VS Code supports, I never see the output tab opening randomly.

By now it is getting automation to quickly close it because I simply don't need the information.

**Comment by snewell92** [comment]
@Martinspire It would be nice if the output was formatted to actually give a compile error, as that is usually what it is trying to report. It should append any errors into the 'Problems' that language services usually dump them in, but instead the language service just throws up all of its output and gets in our way.

So, yes, it _could_ open and be meaningful - but your point about it opening even while you are typing is a good one. The TS language service catches those errors, and then draws a red squiggle - instead of blowing up the output tab.

Perhaps another issue could be opened to explore why this is happening in the first place, and investigate how the ALS is handling errors and logging output - regardless, all of that is outside the scope of this issue. We just want the output to be squelched.
