### ISSUE TITLE
Emails viewed as unknown blocks

### ISSUE THREAD

**Issue by rgolea** [angular/vscode-ng-language-service#1958]
# 🐞 bug report

### Is this a regression?

 This comes with the last version in which we introduce the new control flow syntax.

### Description

 A clear and concise description of the problem...

If you have an anchor tag where you have an email, you get an error that the domain is an unrecognised block

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [?] Angular Language Service server - haven't tested

## Reproduction

1. Open an app and write the code as shown in the picture below
<img width="782" alt="Screenshot 2023-11-08 at 08 49 43" src="https://github.com/angular/vscode-ng-language-service/assets/8843202/b901bddc-915f-4cef-9a62-8885009645ca">

**Expected behavior**

It should ignore it because there are letters in front of the `@` symbol.

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>

Angular CLI: 16.1.0
Node: 18.16.1
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 16.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.1.0
@angular-devkit/core            16.1.0
@angular-devkit/schematics      16.1.0
@angular/cli                    16.1.0
@schematics/angular             16.1.0
rxjs                            7.8.1
typescript                      5.0.4
</code></pre>

Extension Version:
<pre><code>

17.0
</code></pre>

VSCode Version:
<pre><code>

Version: 1.84.1 (Universal)
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:37:18.666Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
</code></pre>

Operating System:
<pre><code>

MacOS X 14.0 (23A344)
</code></pre>

**Comment by dylhunn** [comment]
This is happening because the v17 compiler requires non-block uses of the `@` character to be escaped. This migrations happens automatically when you update to v17.

We probably should disable make the parser skip this warning in the language service for projects not yet on v17.

Here's a workaround for now: if you're not on v17 yet, you can go to the VSCode Marketplace page for the Angular Language Service. Click the arrow next to "Uninstall," and choose "Install Another Version." Then, install `v16.1.8` (or earlier).

**Comment by rgolea** [comment]
Quick question though, @atscott. I see that you're disabling highlight if you don't have support for it. Shouldn't the new control flow syntax be restricted on a full line? That way, if you have a line that starts with `@` and ends with `{`, it's eligible to be highlighted? That way you don't have to disable it for different versions.

I'm not trying to bash on the work you guys are doing, I'm simply curious on how this works under the hood. Thank you!

**Comment by atscott** [comment]
@rgolea It was initially, but you can have the control flow expression and brace on a different line. See https://github.com/angular/vscode-ng-language-service/issues/1945

**Comment by atscott** [comment]
And we do have to completely disable block syntax parsing in the compiler. It will parse _any_ `@` character as the start of a block and tokenize it as an incomplete block. This is necessary to support autocompletion and other language features for when you're still typing the block. For example `@def` should be parsed as a block and we should be able to provide the `defer` completion. Additionally, `@for (let item of ` is also an incomplete `for` block rather than text

**Comment by rgolea** [comment]
Thank you!
