### ISSUE TITLE
Question: What is the status of the extension?

### ISSUE THREAD

**Issue by listepo-alterpost** [angular/vscode-ng-language-service#198]
Hi, @chuckjaz    I noticed that you have not been active for a long time on this project. I'm Interested in whether the project will live or not, thanks.

**Comment by Maximaximum** [comment]
I'm also interested to know if this project is alive yet. As for now, the extension is very buggy, and there have been no code updates for the last 3 months.

@chuckjaz could you please notify if this project is going to live on at all?

**Comment by jtsom** [comment]
I'll add a me too to this - there have been no updates for a while, and there are lots of bugs - including one that breaks intellisense.

**Comment by simonmeusel** [comment]
I looks like there's nobody maintaining this. Somebody should make a fork. I currently do not have time for it, but some bugs are very annoying.

**Comment by Toub** [comment]
@chuckjaz could you answer to this one please?

**Comment by kyliau** [comment]
We will publish a new version that addresses some of the outstanding bugs fixed in upstream [@angular/language-service](https://github.com/angular/angular/tree/master/packages/language-service). In the near future, we plan to move to the new architecture where Angular language service is installed as a [Typescript plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin), instead of Angular hosting its own server. This is pending some requisite bug fixes in Typescript, for example https://github.com/Microsoft/TypeScript/issues/20321.

**Comment by HideDev** [comment]
@kyliau thanks, I'm really looking forward to updates and not just me

**Comment by deftomat** [comment]
@kyliau Hi, any news ? It looks like this project is not in an active development anymore. 😞 
There are a lot of open issues which are crucial (like #250).

**Comment by kyliau** [comment]
Closing this, please track the latest status [here](https://github.com/angular/vscode-ng-language-service/issues/335).
