### ISSUE TITLE
Issue with code diagnostic inside ng-template using coc-angular in nvim

### ISSUE THREAD

**Issue by jotar910** [angular/vscode-ng-language-service#2021]
**Environment:**
- LazyVim (Neovim version: 0.9.5)
- coc-angular
- @angular/language-server version: 17.3.1
- TypeScript version: 5.4.3

**Description:**
I've encountered an issue where the Angular Language Service fails to validate or provide IntelliSense within `ng-template` tags and for structural directives in Angular templates. This issue persists even after switching from lsp angularls to coc-angular, suggesting it might be an underlying issue with the Angular Language Service itself.

**Steps to Reproduce:**
1. Open an Angular project in LazyVim configured with coc-angular.
2. Navigate to a component template that uses `ng-template` or structural directives like `*ngFor` or `*ngIf`.
3. Observe that within the `ng-template` tags, the language service does not provide syntax highlighting, autocompletion, or error diagnostics as expected.

**Expected Behavior:**
The Angular Language Service should provide full language features, including syntax highlighting, autocompletion, and diagnostics, within `ng-template` tags and for structural directives.

**Actual Behavior:**
The language service features seem to be unavailable or not working as expected within `ng-template` tags and for structural directives in Angular templates.

**Additional Context:**
This issue significantly impacts the development experience, as `ng-template` and structural directives are commonly used in Angular projects. I have tried various workarounds, including switching between lsp angularls and coc-angular, without success. It seems to be an issue with how the Angular Language Service interprets or analyzes templates containing `ng-template` and structural directives.

I am looking forward to any suggestions, workarounds, or information on whether this is a known issue being addressed in upcoming releases. Thank you for your support and efforts in maintaining the Angular Language Service.

**Comment by atscott** [comment]
This sounds as though it’s likely your compiler options do not have strict templates enabled. 

We do not actively support or publish the language service for anything other than VSCode. I would suggest seeking debugging help in other forums. If it is determined that there is an issue in the language service that we can fix to help support other IDEs, we can look into it at that time. At the moment, however, there’s not enough information here to determine what the root cause is and it seems possible that it could instead be the coc-angular integration that has an issue rather than the angular language service itself.
