### ISSUE TITLE
Use @angular/language-service from node_modules

### ISSUE THREAD

**Issue by Springrbua** [angular/vscode-ng-language-service#203]
It seems like the @angular/language-service is bundled with the plugin and is still using 5.0.0-beta.5.  
Also, when you node_module contains the @angular/language-service package, the plugin does not seem to work.  
It would be cool, if the plugin could use the installed @angular/language-service from the node_modules.  
This would have multiple advantages:
- The version would be the same as the version of Angular (for example 5.1.1)
- Other editors are already using that package under node_modules. If you want to work with vscode-ng-language-service, the other editors won't work (you have to remove @angular/language-service from node_modules) or this plugin won't work.  
- It should now also be possible to reuse the TypeScript language service instance, as [#7482](https://github.com/angular/angular/issues/7482) is now closed.  

@chuckjaz what do you think about it?

**Comment by chuckjaz** [comment]
> t would be cool, if the plugin could use the installed @angular/language-service from the node_modules.

This was the original intent but the code was disabled because intermediate builds of the language service did not go though enough testing and were periodically very broken.

We are going to significantly increase the number of tests we can run on the language service starting in early Jan as well as always be using the latest language service for internal Google developers. After I no longer have to had validate new versions I will re-enable this.

The changes to support using the plugin API should all be landed soon. I am in discussions now with the TypeScript team to ensure all the features needed are landed in TypeScript and VS Code.

**Comment by Springrbua** [comment]
@chuckjaz thanks for the information, can't wait for this to land in vs code :)

**Comment by GeorgeKnap** [comment]
Is this issue related to this error I'm getting?
![vscode](https://user-images.githubusercontent.com/11920691/35723810-f5b774dc-07fb-11e8-8b69-92db8296c7cc.PNG)
Angular doesn't recognize 3rd party package components in VS Code. In Visual Studio Community it works fine.

**Comment by Springrbua** [comment]
@chuckjaz The plugin still seems to use Angular 5.2.2. Is there any update on this issue?

**Comment by Springrbua** [comment]
Thanks a lot. I'll have to check how to build and install it in vscode.
Hopefully, the PR gets accepted soon, so that anyone can easily update the plugin.

**Comment by kyliau** [comment]
The new extension loads @angular/language-service from the workspace (node_modules) by default. There's also a new config `ngdk` for manually overriding the path.
It falls back to the bundled version if the language service could not be found anywhere in those paths.
