### ISSUE TITLE
The language service is a separate service from TypeScript and runs a duplicate version of the TypeScript language service

### ISSUE THREAD

**Issue by angelozerr** [angular/vscode-ng-language-service#25]
The language service is a separate service from TypeScript and runs a duplicate version of the TypeScript language service

See [#7482](https://github.com/angular/angular/issues/7482) for a more details status of the current progress.

I create this issue because I would like to integrate your work inside Eclipse IDE.

**Comment by chuckjaz** [comment]
This is currently blocked by a couple things.

1. The extensibility module must be in a published version of TypeScript. It is currently in a development branch.
2. The LanguageService API needs to be extended to handled requests that are not generated by TypeScript (e.g. diagnostics that are tagged from Angular and completion results for language elements not in TypeScript).

The TypeScript team is aware of both of these issues are are actively working on them.

The goal is to make these one service, instead of two where the Angular typescript service just plugs into TypeScript's API.

**Comment by kyliau** [comment]
Closing this, since the language service is already a tsserver plugin - albeit without support for external HTML template.
