### ISSUE TITLE
[Angular] The template context does not have an implicit value

### ISSUE THREAD

**Issue by wangming-0215** [angular/vscode-ng-language-service#251]
Hi, here's an error I encounter regularly. Here is my code:
![qq 20180519023703](https://user-images.githubusercontent.com/21071580/40252025-995f8084-5b0d-11e8-9709-ee328dfc8a2e.png)
![qq 20180519023736](https://user-images.githubusercontent.com/21071580/40252032-9c975d80-5b0d-11e8-8fdf-c63be25d92e8.png)

**Comment by prasworld** [comment]
Check this solution

https://github.com/Apress/pro-angular-6/issues/6

**Comment by ayazhafiz** [comment]
I don't think this is a bug. In a static analysis, the type of the context used by the embedded template (`TemplateRef`) can't be refined more than the type parameter of the `TemplateRef` used by the structural directive - in this case, since the type of the context is specified to be `Object`, the language service doesn't have a good way of knowing that the actual context used is `CounterDirectiveContext`. Specifying `CounterDirectiveContext` does get rid of the diagnostic message.

I think an effective action we can take is to provide a more helpful diagnostic message, perhaps including a suggestion to refine the type of the context used by the `TemplateRef`.
