### ISSUE TITLE
autocomplete on click should suggest (click)

### ISSUE THREAD

**Issue by MingxunBai** [angular/vscode-ng-language-service#302]
When i want to add `(click)` attribute with `click`, there is no suggestion:
![image](https://user-images.githubusercontent.com/16555379/49276395-5f4fea00-f4b9-11e8-8d7d-7d8a1a8ab40b.png)
However, it will suggest when beginning with `(`:
![image](https://user-images.githubusercontent.com/16555379/49276483-9f16d180-f4b9-11e8-8a28-eee7b88a2b7b.png)

**Comment by iamcco** [comment]
It should also suggest `*ngif`  when type `ngi`, with latest version I have to type `*ngi`

**Comment by ayazhafiz** [comment]
I think this was an intentional change with https://github.com/angular/angular/pull/34445.

**Comment by ayazhafiz** [comment]
cc @kyliau @andrius-pra @ivanwonder thoughts on supporting or closing this?

**Comment by kyliau** [comment]
I am in favor of the approach in https://github.com/angular/angular/pull/34445.
The main reason is because the suggestion list is _overly broad_ with the original implementation.
Take the following example:
```html
<div |></div>
```
where `|` is the cursor position.
At this point, we are asking the editor, what are the possible candidates here?
The result is a long list of items (html properties/attributes/events without or without binding), and such long list hurts *discoverability*.

Since this issue was created before the autocomplete behavior was revamped, I suggest we continue the discussion in https://github.com/angular/vscode-ng-language-service/issues/521.

**Comment by andrius-pra** [comment]
I'm also prefer the current behavior. It's easier to write `[`, `[(` or `(` character and choose relevant value from small list of  suggestions that valid in your context.

**Comment by ivanwonder** [comment]
> I'm also prefer the current behavior. It's easier to write `[`, `[(` or `(` character and choose relevant value from small list of suggestions that valid in your context.

Agree.
and I think it's also good to provide `bind-`, `on-`, etc on `<div |></div>`.
