### ISSUE TITLE
Incorrect Errors Which Require Restarting VS Code to be cleared

### ISSUE THREAD

**Issue by waelkdouh** [angular/vscode-ng-language-service#311]
VS Code detects that there is an error in my Angular application (html, ts, etc.) and displays red squiglies inside different files. The interesting part is that the angular compiler compiles the project successfully and the application runs fine. The solution is to close the file and reopen it. In some cases I have to restart VS Code to resolve the issue. Its really a huge inconvenience right now that needs to be resolved as it almost makes the extension unusable.

**Comment by Nemesis19** [comment]
I have the same problem. I solve it by closing/reopening the file, sometimes it's frustrating because you are not sure if the error is valid or not.

**Comment by waelkdouh** [comment]
Yeah it makes the experience of developing Angular applications under VS Code almost unusable as I never know when there is an error or not. It baffles me that this issue haven't been solved yet although it has been occurring for a long time.

**Comment by waelkdouh** [comment]
> I have the same problem. I solve it by closing/reopening the file, sometimes it's frustrating because you are not sure if the error is valid or not. Happens both on template files and ts files.

Yeah it makes the experience of developing Angular applications under VS Code almost unusable as I never know when there is an error or not. It baffles me that this issue haven't been solved yet although it has been occurring for a long time.

**Comment by adorep** [comment]
Same here, the idea behind this extension is very usefull, but not beeing able to remove false positives from the error list (which in my opinion is a problem of vscode and not of this extension) and the extreme cost of performance are a showstopper.

In fact the error list is what i am using this extension for and an easy way to remove false positives from the list or ignore specific files would be awesome.

Other features like F12 and autocompletion are so slow that it is much faster for me to navigate where i want to go by hand and type what i want instead of waiting for the completion popup to appear.

**Comment by kyliau** [comment]
This is because there are some differences in the way language service provides real time diagnostics vs ngc compilation. With the new rewrite coming out soon for Ivy, the errors should be consistent.

**Comment by kyliau** [comment]
There are two issues here:

1. Angular language service not updating diagnostics as the file changes.
2. Diagnostics produced by the language service are different from those produced by the compiler.

(2) is a longer term effort to integrate Ivy into the language service. Based on the issue title and the discussion above, I will focus on (1) in this ticket.

We have solved (1) by
1. Update diagnostics in real time without the need to restart
2. Added a restart command so that the extension could be reloaded independent of the editor.

We hope there is never a need to restart, but added the command in case users really need it.

A new version of the extension will be released in conjunction with v9, meanwhile you could try out the RC version by downloading the binary from the Release page.

**Comment by kyliau** [comment]
The new extension is now live. Please download it from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
I'd like to close this issue for now. Please open a new issue for any lingering bugs, thank you!
