### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by rpd10** [angular/vscode-ng-language-service#322]
When enabling this extension, we are seeing high memory consumption, on the order of 2GB for the CodeHelper process that relates to this extension.  This is a fairly large angular project.

Mac 10.14, 16GB RAM.  VSCode Version 1.33.1, plugin version 0.1.11

Found using Activity Monitor, isloating the PID of the high-memory process, then `ps aux | grep <pid>`, which points to `/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/rpd10/.vscode/extensions/angular.ng-template-0.1.11/server/server.js --node-ipc --clientProcessId=26702`

Let me know what other information I can provide.

**Comment by kyliau** [comment]
@rpd10 Could you please let me know which version of Angular your project uses?

**Comment by rpd10** [comment]
We currently use @angular/core@7.2.14, at the time of this writing it was probably an earlier version of Angular 7.

**Comment by kyliau** [comment]
That's what I suspected. The problem is most likely due to incompatible Typescript versions - the language service itself bundles a specific version of Angular and Typescript, which might conflict with the version used in your project.
I've just released a beta version of the extension - do you mind trying it and let me know if this is still a problem?
You can download the `ngls.vsix` binary from https://github.com/angular/vscode-ng-language-service/releases/tag/v0.800.0-rc.0 and install it in VS Code with the command
```
> Extensions: Install from VSIX
```

**Comment by kyliau** [comment]
Released v0.800.0 that fixed performance regression.
Multiple beta users confirmed that language service works well with Angular v7 and v8.
Please open another issue if this is not the case.
https://github.com/angular/vscode-ng-language-service/releases/tag/v0.800.0

Related issues:
- https://github.com/angular/vscode-ng-language-service/issues/329
- https://github.com/angular/angular/issues/27904
