### ISSUE TITLE
Identifier 'x' refers to a private member of the component

### ISSUE THREAD

**Issue by mostafabita** [angular/vscode-ng-language-service#324]
I have created a component with a class like this:
```
export class MessagesComponent implements OnInit {

  constructor(private messageService: MessageService) { }

  ngOnInit() {
  }
}
```
And a view like this:
```
<div *ngIf="messageService.messages.length">
   <div *ngFor="let message of messageService.messages">
    {{message}}
  </div>
</div>
```
The extension doesn't identify 'messageService' defined in constructor while it is accessible and I don't have any runtime error.

### Error Message:
_`Identifier 'messageService' refers to a private member of the component`_

**Comment by jsarlo** [comment]
Are you using AoT or JiT compiling?

**Comment by kyliau** [comment]
Private members are designed to be **inaccessible**, so this error message is correct.
The reason you didn't run into runtime error, as suggested by @jsarlo, is likely because you're using JIT.
For more info, please see https://stackoverflow.com/questions/34574167/angular2-should-private-variables-be-accessible-in-the-template
From the conversation, this seems working as intended, please reopen otherwise.
