### ISSUE TITLE
Locking app.asar and electron.asar

### ISSUE THREAD

**Issue by Mackignacio** [angular/vscode-ng-language-service#328]
When building package for electron this is the error I get form the terminal.
![image](https://user-images.githubusercontent.com/12345233/57291471-1e0bd800-70f2-11e9-9511-903b09439fe7.png)

At first I suspected VSCode is the one locking the file because when I close VSCode and run `npm run build` on my command line tool it will finish the build. Then I try to search deeper and I found out that `angular services` extension is the culprit as seen in this screenshot. Using **Lock Hunter** you can see what file locking the `.asar` files.

![image](https://user-images.githubusercontent.com/12345233/57291268-af2e7f00-70f1-11e9-8f98-4fb157609104.png)

### Thank you

**Comment by markonyango** [comment]
So good you caught that. It has been driving me nuts during my daily work: every time I wanted to build my Electron container or actually clean the release folder, I had to close VS Code because of it. This is quite annoying. This actually made me wonder whether the output folder of the Electron build process was being watched by VS Code and lo and behold: if you add the output folder to the ignore list, the build process finishes even with VS Code still open.

`
"files.watcherExclude": {
  "**/.git/*/**": true,
  "**/.git/objects/**": true,
  "**/.git/subtree-cache/**": true,
  "**/app-builds": true,
  "**/dist": true,
  "**/node_modules/*/**": true,
  "**/release": true
}`

My output folder is called **release**.

**Comment by Mackignacio** [comment]
So where can I put this json?
`"files.watcherExclude": { "**/.git/*/**": true, "**/.git/objects/**": true, "**/.git/subtree-cache/**": true, "**/app-builds": true, "**/dist": true, "**/node_modules/*/**": true, "**/release": true }`
 On the settings.json file?

**Comment by ChrisKader** [comment]
Using 'Lock Hunter' I found out that (in my case) its not VS Code itself locking the app.asar file, rather, an extention I use called "Vetur".

![image](https://user-images.githubusercontent.com/633360/64353914-20107580-cfc4-11e9-92b4-f6b0ec004ba3.png)

Adding `**/dist_electron/*/**` to the exclude settings in VS Code blocked the extension from locking said file and allowed me to build.

**Comment by faserg1** [comment]
I think that manually adding exclude folders is not a solution of o problem at all.

**Comment by faserg1** [comment]
Also exluding files does not help for me. Extension lock files anyway.
