### ISSUE TITLE
Cannot find user-defined Angular directives

### ISSUE THREAD

**Issue by mjbates7** [angular/vscode-ng-language-service#358]
Hello,

I have created a basic directive (appBetterHighlight following a tutorial) using the CLI service.. however trying to use this within my html view, the view doesn't know about non-angular directives.

**custom directives (not found)**
![image](https://user-images.githubusercontent.com/4522738/63277038-78ddcf80-c29c-11e9-92f3-480be094e4bd.png)

**built in angular directives (found)**
![image](https://user-images.githubusercontent.com/4522738/63277057-82673780-c29c-11e9-8ec9-b13a72f15450.png)

You can reproduce this by creating a new application via the CLI and a directive via the CLI

Is this feature supported / any plans for it to be supported?

**Comment by ayazhafiz** [comment]
I'm pretty sure this a bug, because we currently look for all selectors matching on directives in an NgModule. However, the language service expects to be rewritten soon to use Angular's new Ivy compiler, so we should probably wait to fix this when Ivy becomes the new backbone of the language service.

What do you think @kyliau?

**Comment by kyliau** [comment]
Could you please confirm that the directive you're expecting is actually part of the NgModule you're working with?

**Comment by ayazhafiz** [comment]
I am observing this issue when the directive is part of the NgModule. I think the example @mjbates7 is giving is from https://angular.io/guide/attribute-directives#write-the-directive-code which is easy to repro.
