### ISSUE TITLE
Extension failed to load angular plugin from nested folder.

### ISSUE THREAD

**Issue by andrius-pra** [angular/vscode-ng-language-service#369]
The extension(v0.900.0-next.0) failed to load @angular/language-service plugin when angular project is in a child folder. It only tries to load from root of workspace.

Steps to reproduce:
```
mkdir root
cd root
ng new test-ng-ls --routing=true --style=less
cd test-ng-ls
ng update @angular/core@9.0.0-next.2 @angular/cli@9.0.0-next.1 codelyzer
code ..
```

Environment:
```
@angular/language-service@~9.0.0-next.2
angular.ng-template: v0.900.0-next.0
```

**Comment by jpike88** [comment]
@kyliau having the exact same problem here. It's preventing me from using the plugin at all

I have a workspace structure like so:

```
workspace root -  
                        - client (contains tsconfig.json, angular.json etc)
                        - server (contains just a tsconfig.json)
                        - shared (just .ts files)
```

The plugin doesn't recognize my client folder.

Installing @angular/language-service in the root folder results predictably in errors across all my components (```Component '...' is not included in a module and will not be available inside a template```)... so that isn't a valid workaround.

**Comment by jpike88** [comment]
@kyliau I should also add, I have a tsconfig.json in my root directory.

From inspecting your plugin's code, there appears to be a variable called ```pluginProbeLocation```, but it never gets set.

https://github.com/angular/vscode-ng-language-service/blob/acc2a70a80efa16ab876e38bfd8de508afb8915a/server/src/project_service.ts#L45

So the solution maybe is that some sort of override needs to be set, in order to ensure that ```@angular/language-service``` gets loaded from the correct subdirectory.

Can you please shed some light on this? I'd imagine quite a few developers use a workspace where the angular project is in a subdirectory.

**Comment by jpike88** [comment]
@kyliau can I get an an idea of whether this issue has any level of priority? If not, I'll attempt a fix myself when I get the time. However, I don't want to if you can conceive of something much faster, as this plugin stuff is a little alien to me.

**Comment by andrius-pra** [comment]
I installed `@angular/language-service` in a workspace root and it was enough to fix this issue.
```
mkdir root
cd root
yarn add --dev @angular/language-service@next // <-- Added this command
ng new test-ng-ls --routing=true --style=less
cd test-ng-ls
ng update @angular/core@next @angular/cli@next codelyzer
code ..
```

**Comment by jpike88** [comment]
@andrius-pra if I do that, all my components get this error:

```Component 'exampleComponent' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration.```

It's like it's not aware of my app.module.ts file.

**Comment by jpike88** [comment]
After much pain, I found the issue. It's related to ANOTHER language service bug. I made sure all my components weren't being exported using ```export default```, and it worked.

https://github.com/angular/angular/issues/32451
