### ISSUE TITLE
Support TypeScript requests

### ISSUE THREAD

**Issue by bergerbo** [angular/vscode-ng-language-service#503]
**Describe the bug**

Hello team !

I am trying to get the language server working for an editor my team is working on.
We are able to launch it without problem and it serves angular specific request perfectly (ie:  textDocument hover/definition in an inlined template `@Component` annotation).
 
However basic typescript requests (ie: everything else) are answered with a simple `null`.

**To Reproduce**

Here is a Dockerfile supposedly setting up everything required that allows to reproduce.

```Dockerfile
FROM registry.hub.docker.com/library/node:12.13.1

RUN apt update && apt install -y wget unzip && rm -rf /var/lib/apt/lists/*

# install angular-language-service
WORKDIR /tmp
RUN wget https://github.com/angular/vscode-ng-language-service/archive/v0.900.2.zip
RUN unzip v0.900.2.zip
WORKDIR /tmp/vscode-ng-language-service-0.900.2
RUN yarn
RUN yarn compile

# move it to opt
RUN mv /tmp/vscode-ng-language-service-0.900.2/ /opt/vscode-ng-language-service
RUN rm -rf /tmp/*

# create angular project from cli for config files
WORKDIR /tmp
RUN npm install -g @angular/cli
RUN ng new project --interactive false
WORKDIR /tmp/project

ENV TSC_NONPOLLING_WATCHER true

# start server
ENTRYPOINT node /opt/vscode-ng-language-service/server/out/server.js \
    --ngProbeLocations /opt/vscode-ng-language-service/server \
    --tsProbeLocations /opt/vscode-ng-language-service \
    --stdio --logFile /var/log/languageserver.log --logVerbosity verbose
```

**Expected behavior**

Typescript requests should be served properly by the language service.

**Logs**

Logs are very dense and not very useful. Everything seems to be working without error.

At first I thought that the problem might come from [project_service.ts:92](https://github.com/angular/vscode-ng-language-service/blob/master/server/src/project_service.ts#L92)
```ts
let project = this.tsProjSvc.getDefaultProjectForFile(
   scriptInfo.fileName,
    // ensureProject tries to find a default project for the scriptInfo if
    // it does not already have one. It is not needed here because we are
    // going to assign it a project below if it does not have one.
    false  // ensureProject
);
```
Because it was causing projects to be inferred for no apparent reason. 
However setting ensureProject to `true` did not fix the problem at all (it did prevent projects to be inferred, but the ts requests still return `null`).

Another notable thing in the logs is that ProjectRootPath is always undefined even though there is a project. Example: 

```
Info 115  [14:37:46.45] -----------------------------------------------
Info 115  [14:37:46.45] Open files:
Info 115  [14:37:46.45]         FileName: /tmp/project/possible_solution.component.ts ProjectRootPath: undefined                                                                                                    
Info 115  [14:37:46.45]                 Projects: /tmp/project/tsconfig.json
Info 115  [14:37:46.45]         FileName: /tmp/project/validator.ts ProjectRootPath: undefined
Info 115  [14:37:46.45]                 Projects: /tmp/project/tsconfig.json
Info 115  [14:37:46.45]         FileName: /tmp/project/tester.ts ProjectRootPath: undefined
Info 115  [14:37:46.45]                 Projects: /tmp/project/tsconfig.json
Info 115  [14:37:46.45]         FileName: /tmp/project/answer.component.ts ProjectRootPath: undefined
Info 115  [14:37:46.46]                 Projects: /tmp/project/tsconfig.json

```

I know your main target is the vscode extension, but I wouldn't say no to a little help here !

Am I missing something obvious ?

Thanks a lot,
Boris

**Comment by ayazhafiz** [comment]
`ProjectRootPath` being undefined may not be the issue, because it is sometimes undefined for "working" instances of the language server as well.

If I recall correctly, not responding to TypeScript queries is the expected behavior; the language server enables the Angular language service to only respond to Angular queries:

https://github.com/angular/vscode-ng-language-service/blob/d6e9fc2b1deb9871f8ddccc1c47fe3eec558fd20/server/src/project_service.ts#L47-L52

The configuration options are specified at https://github.com/angular/angular/blob/d0a04bf30980a60629c22b332de29040cea8e703/packages/language-service/src/ts_plugin.ts#L16-L24. There is another case where the Angular language service will return requests for TypeScript queries, but this only works when the project has no external templates and must be configured in `tsconfig.json`.

In order to get TypeScript language service support in your editor, you will have to provide a separate TypeScript language server for your editor's LSP.

@kyliau do you have more insight? apologizes if I'm mistaken anywhere.

**Comment by kyliau** [comment]
Yes, the Angular language service is designed specifically to support Angular projects only, not TypeScript.

This is because of many reasons:
1. The need to support non-TypeScript files (HTML for external templates)
2. Performance
3. Stability

There is one mode that supports both Angular + TypeScript, but that assumes you don't need support for HTML files. You can launch this mode simply by adding a "local" plugin to `tsconfig.json`.
In this case, there is no need to install the Angular language server at all.

```
{
  "compilerOptions": {
    "plugins": [
      { "name": "@angular/language-service"}
    ]
  }
}
```

Like @ayazhafiz mentioned, if you want the full support, you'll have to install both TypeScript and Angular servers.

**Comment by bergerbo** [comment]
I've tried using a typescript language server with the `@angular/language-service` plugin and everything works fine for our use case (we are only supporting inline templates for now).

Thanks a lot for your quick answers !
