### ISSUE TITLE
index in *ngFor not recognised as a number

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#514]
latest version of the plugin and latest angular 8.x

![Screen Shot 2019-12-18 at 1 45 43 pm](https://user-images.githubusercontent.com/9585787/71062285-b6942b80-219c-11ea-8350-ea7b2d07fbb0.png)

activeTabIndex is defined in the component:
```public activeTabIndex: number = 0;```

There is some sort of type issue here I guess

**Comment by ayazhafiz** [comment]
This was fixed in https://github.com/angular/angular/pull/34089; see https://github.com/angular/vscode-ng-language-service/issues/460 for some previous discussions.

You will need version [9.0.0-rc.5](https://github.com/angular/angular/releases/tag/9.0.0-rc.5) of the language service in order to get this fix.

**Comment by jpike88** [comment]
sweet thanks

**Comment by jpike88** [comment]
does my project need to be above angular 8 to use this? I updated the compiler-cli, compiler and and language service to 9.0.0-rc.5 in my root folder (not in my angular project folder which is in a subfolder), and that should work right?

**Comment by ayazhafiz** [comment]
Just the language service needs to be at version 9.0.0-rc.5 -- I think that should work, as extension just tries to find the language service at the open workspace. You can check the version being used by opening the VSCode terminal > Output Tab > Dropdown on the right > Angular Language Service.
