### ISSUE TITLE
"Extract to method in class" in inline template doesn't behave correctly

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#533]
**Describe the bug**

"Extract to method in class" ability doesn't seem to behave correctly on a inline template function call. In below 

**To Reproduce**

see GIF for clear reproduction. the inline template is missing the function ```addChildElement``` and is listed correctly. Using the autosuggested 'extract method' call in context menu removes the whole ```template``` properly and swaps it with a ```templateURL``` one, with a weird function call.
 
![wat](https://user-images.githubusercontent.com/9585787/71540948-89116400-298c-11ea-918f-641ecfa621b0.gif)

**Comment by ayazhafiz** [comment]
Do you know if this has ever behaved correctly in the past?

**Comment by jpike88** [comment]
No

**Comment by ayazhafiz** [comment]
I don't think this is an issue with an extension, as it occurs with the extension uninstalled as well. VSCode pulls out the contents of the entire string into a new function and replaces the original string with that function call.

Closing because this is functionality related to VSCode's TS/JS features and outside the scope of the Angular language service extension.
