### ISSUE TITLE
Template Syntax Highlighting broken

### ISSUE THREAD

**Issue by DerHerrGammler** [angular/vscode-ng-language-service#541]
Syntax highliting in templates is broken after a few conditions.
One Condition ist the reseved words like 'class' is used as pipe name:
![grafik](https://user-images.githubusercontent.com/30802629/72195759-5cd9f680-3414-11ea-900f-d4e922f3db61.png)
Another condition is the use of Arrays in templates
![grafik](https://user-images.githubusercontent.com/30802629/72195796-9ca0de00-3414-11ea-86c4-b99b8f871958.png)

**Comment by ayazhafiz** [comment]
The second will be fixed by #540.

**Comment by ayazhafiz** [comment]
The first issue may not be fixable because of https://github.com/microsoft/vscode/issues/20488. Maybe this makes a grammar for property bindings a non-starter.

@DerHerrGammler what is the pipe you are using that requires the class syntax? More specifically, is it provided by any native Angular libraries?

**Comment by dannymcgee** [comment]
> The first issue may not be fixable because of [microsoft/vscode#20488](https://github.com/microsoft/vscode/issues/20488). Maybe this makes a grammar for property bindings a non-starter.

I think a good long-term solution to this would be to define a syntax that's essentially a limited subset of JavaScript, and embed that syntax in the template bindings instead of just embedding the entire JavaScript grammar. In addition to fixing bugs like this, we could also define more accurate grammar scopes for the Angular-specific stuff like pipes and the `as value` syntax which would be a win-win.

**Comment by luboslav** [comment]
Syntax highlighting in latest version is also broken in angular binding (with square brackets).

![syntax-highlight](https://user-images.githubusercontent.com/7914658/72422245-5b952a80-3782-11ea-8aa0-5c30534981c2.PNG)

**Comment by ayazhafiz** [comment]
@luboslav This is intentional. The content is being highlighted as inline JavaScript.

**Comment by tieppt** [comment]
Also broken when access object through indexes
![image](https://user-images.githubusercontent.com/7151365/72797409-a7a90900-3c73-11ea-840a-5e7804da7523.png)

**Comment by dannymcgee** [comment]
@ayazhafiz I've been thinking about the issue with embedded grammars getting stuck and the potential solution I mentioned earlier in this thread, and I made a really rough proof of concept that seems promising.

The basic idea is:
- We embed our own subset of the JavaScript grammar instead of the full JS grammar, limited to just the syntax that's actually valid in Angular templates
- We have two _versions_ of that grammar, one which recognizes single quotes as an end condition, and one that recognizes double quotes
- For each template binding, we inject the correct grammar depending on whether the value was bound with double or single quotes

The hard (or annoying) part of that equation is having to maintain two nearly identical grammars for the JavaScript subset. The solution I came up with was to generate the JSON files dynamically with TypeScript, where each grammar "repository" is defined in a separate file. Then you can just swap out the imports for the handful of repositories that actually need to be different between the two versions. The proof of concept for that is here: https://github.com/dannymcgee/vscode-grammar-from-ts-experiment

There are some other advantages to doing it this way, namely much better code organization and much more readable regex patterns since they can be written as regex literals and benefit from syntax highlighting. And the additional benefits of defining our own grammar for the scripting language is that we can add more accurate grammar scopes for things like pipes and the `as local-val` syntax.

Do you think this is a reasonable solution? And if so, any guidance on how to split up my PRs for ease of review?

**Comment by ayazhafiz** [comment]
@dannymcgee thanks for taking the time to do this. I like your idea of a template syntax grammar; it's definitely the "correct" way to do it.

I'm not sure that we need two separate grammars for single and double quotes. I guess the case where this matters is if someone uses single quotes inside an attribute itself demarcated by single quotes (and symmetrically for double quotes), though I wonder how common this pattern is -- if it's not very common or does not significantly impact the stability of the grammar, it may not be worth the cost of maintaining two disjoint grammars. I'm not opposed to compiling the grammar from TypeScript definitions if the way to move forward is with two grammars. What do you think?

For PRs, incremental features should work fine. Looking at your PoC, for example, there could be a PR for all numeric things, then one for all objects, etc. After everything gets merged we can swap out the call to the JS grammar to the template syntax grammar.

I will open another issue for this where can discuss further.

**Comment by ayazhafiz** [comment]
Closing this issue as the second bug presented in https://github.com/angular/vscode-ng-language-service/issues/541#issue-548355331 and https://github.com/angular/vscode-ng-language-service/issues/541#issuecomment-576618644 have been fixed in #542. A discussion for the first bug (leaking JavaScript grammar) will be tracked in #571.

If you are experiencing further issues with the grammar or would like to request a feature, please open a new issue.
