### ISSUE TITLE
Emmet support for inline templates in VS Code and other editors that support emmet today

### ISSUE THREAD

**Issue by johnpapa** [angular/vscode-ng-language-service#561]
Emmet support for inline templates in VS Code and other editors that support emmet today

**Comment by ayazhafiz** [comment]
Could you elaborate on what the feature you would like to see is, per the details requested in the feature request template (https://github.com/angular/vscode-ng-language-service/blob/master/.github/ISSUE_TEMPLATE/feature_request.md)?

**Comment by kresdjan** [comment]
Kind of mind-blowing that it isn't supported.

**Comment by johnpapa** [comment]
@ayazhafiz yes. All emmet features for html should work in inline template. Just as they do in html templates in vs code. 

Similar works in JSX for react or .vue files for vue.

**Comment by ayazhafiz** [comment]
I'm surprised this doesn't come for free in VS Code. We already filetype inline templates as HTML (for example, comment shortcuts in inline templates are HTML). Strange that VS Code doesn't apply HTML emmet shortcuts there too.

**Comment by ayazhafiz** [comment]
@johnpapa FWIW there is a workaround; see https://github.com/Microsoft/vscode/issues/34736#issuecomment-345015470. You can trigger emmet completions in inline templates by specifying `"emmet.triggerExpansionOnTab": true` in VSCode's settings.json. The downside is you won't get emmet completions via a dropdown.

The problem is that emmet is triggered on filetype rather than language scope. So even though we specify that inline templates are HTML, Emmet is not triggered because they are located in a TypeScript file. It appears that this is no-fix on VSCode's side for now.

**Comment by atscott** [comment]
This does seem to be possible with [request forwarding for embedded languages](https://code.visualstudio.com/api/language-extensions/embedded-languages#request-forwarding). The summary is that our client implementation would:

1.  intercept the request for completion
2. find that the location is inside an inline template
3. create a virtual document with just the html contents
4. forward the completion request along to the other completion providers (i.e. Emmet). 

I've been able to get this working locally so I think this is something we can do in the near-ish future.
