### ISSUE TITLE
Editor buffer out of sync with file on disk

### ISSUE THREAD

**Issue by aditbharadwaj** [angular/vscode-ng-language-service#632]
**Describe the bug**

The Angular Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted. Even after restarting the Vscode the service keeps on crashing.

**To Reproduce**

1. Service Crashing after 5 minutes of working

**Logs**
1. Console Log
[output log of the vscode.txt](https://github.com/angular/vscode-ng-language-service/files/4197743/output.log.of.the.vscode.txt)
2. Log File
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/4197748/nglangsvc.log)

**Screenshots**
![als](https://user-images.githubusercontent.com/6751554/74425914-75598880-4e7a-11ea-913f-c22b8cecfab8.PNG)

**Comment by ayazhafiz** [comment]
I think I know what is causing this, but I cannot reproduce the error. Are you able to show what you were editing when the crash happened?

**Comment by andrius-pra** [comment]
Could you try to remove "tslint-language-service" from your tsconfig.json?

**Comment by ayazhafiz** [comment]
@andrius-pra I loaded a project with 'tslint-language-service', and while the package could not be found, it didn't crash the language service. I could be wrong though.

There are two kinds of errors in the log. One of them is the result of a failed assertion during the editing of a source file (https://github.com/microsoft/TypeScript/blob/950b36192a10f5dac52993f1e29e62cbac513853/src/compiler/parser.ts#L8052). I think this may be caused by how we pass changes to source files: https://github.com/angular/vscode-ng-language-service/blob/fd3dfd92e67b57622955af09985e2d073c6cf336/server/src/session.ts#L233-L239

which changed since #553.

**Comment by andrius-pra** [comment]
@ayazhafiz, I have reproduced this issue. 
![bug](https://user-images.githubusercontent.com/17968027/74551579-1d934e00-4f5c-11ea-986c-da82edf9bd48.gif)

**Comment by ayazhafiz** [comment]
Nice!

**Comment by aditbharadwaj** [comment]
> I think I know what is causing this, but I cannot reproduce the error. Are you able to show what you were editing when the crash happened?

i was actually editing two files in split view and if u want the content i was basically calling variables and checking their definition. that's it. mainly it was whenever i was in split screens with multiple files it crashed for me.

**Comment by kyliau** [comment]
Thank you for the repro - this is caused by my recent PR https://github.com/angular/vscode-ng-language-service/pull/476
I don't remember why the change was needed to remove `getExternalFiles()`. I'll try to undo the change and fix this.
