### ISSUE TITLE
Intelisense in cdkVirtualFor of cdk-virtual-scroll-viewport not working

### ISSUE THREAD

**Issue by MichalK6677** [angular/vscode-ng-language-service#737]
Intelisense in cdkVirtualFor of cdk-virtual-scroll-viewport not working.

Angular cdk virtual scroll:
https://material.angular.io/cdk/scrolling/overview

![image](https://user-images.githubusercontent.com/3100059/79633137-ef9cd680-8163-11ea-893f-8f109d1b0c33.png)

![image](https://user-images.githubusercontent.com/3100059/79633145-05120080-8164-11ea-855c-18f17b28d567.png)

![image](https://user-images.githubusercontent.com/3100059/79633160-10fdc280-8164-11ea-8f97-098d49460f2e.png)

**Comment by ayazhafiz** [comment]
This is a known problem. The language service cannot infer the type of the variable being iterated over with `of`, because in the definition of `cdkVirtualFor` this variable is a generic and we are currently not smart enough to resolve generic values automatically.

This will be fixed when the language service moves to an Ivy backend.

**Comment by kyliau** [comment]
This has been fixed by the new Ivy-native language service, released in [v11.1.0](https://github.com/angular/vscode-ng-language-service/releases/tag/v11.1.0).
It's an opt-in feature for now, please give it a try and let us know if you have any feedback.
Please make sure your project has [`strictTemplates`](https://angular.io/guide/angular-compiler-options#stricttemplates) enabled in `angularCompilerOptions`.
