### ISSUE TITLE
'component' is not a known element

### ISSUE THREAD

**Issue by willianferreiradev** [angular/vscode-ng-language-service#862]
I have several modules that use the same modules, so I made a general-modules.ts file. And in each module that I use these same modules, I import this file. I believe that the extension is not recognizing, because the modules themselves are not being imported directly into the file
![Captura de tela_2020-07-17_09-27-04](https://user-images.githubusercontent.com/33581079/87786189-e4635080-c80f-11ea-877c-85094bc204ad.png)
![Captura de tela_2020-07-17_09-27-38](https://user-images.githubusercontent.com/33581079/87786191-e5947d80-c80f-11ea-81da-699932f1eb57.png)
![Captura de tela_2020-07-17_09-28-24](https://user-images.githubusercontent.com/33581079/87786193-e62d1400-c80f-11ea-9421-919f047f7a26.png)

I'll send the prints as I did, and to reproduce it, just do the same as I did

**Comment by ayazhafiz** [comment]
probably a duplicate of #645

**Comment by willianferreiradev** [comment]
> probably a duplicate of #645

It is not the same mistake. If you can read it, read it carefully and see the difference

**Comment by thuyetngx** [comment]
+1 i have the same issue

**Comment by kyliau** [comment]
This has been fixed by the new Ivy-native language service, released in [v11.1.0](https://github.com/angular/vscode-ng-language-service/releases/tag/v11.1.0).
It's an opt-in feature for now, please give it a try and let us know if you have any feedback.
For the best editor experience, please make sure your project has [`strictTemplates`](https://angular.io/guide/angular-compiler-options#stricttemplates) enabled in `angularCompilerOptions`.
In case you run into similar bug, please file a new issue. I'll close this for now.

**Comment by atscott** [comment]
Closing as resolved, see Keen's comment above https://github.com/angular/vscode-ng-language-service/issues/862#issuecomment-765010735
