### ISSUE TITLE
Started getting "is not a known element" in vscode editor, yet ng serve works fine

### ISSUE THREAD

**Issue by singulli1** [angular/vscode-ng-language-service#887]
**Describe the bug**

Started getting "is not a known element" in vscode editor, yet ng serve works fine. 
I suspect this is due to an error during @angular/language-service execution.

excerpt from nglangsvc.log:

Info 9    [11:32:55.796] Loading global plugin @angular/language-service
Info 10   [11:32:55.796] Enabling plugin @angular/language-service from candidate paths: c:\Users\scott\.vscode\extensions\angular.ng-template-0.1000.7\server\node_modules\@angular\language-service\bundles\language-service.js,c:/Users/scott/.vscode/extensions/angular.ng-template-0.1000.7/node_modules/typescript/lib/tsserverlibrary.js/../../..
Info 11   [11:32:55.796] Loading @angular/language-service from c:\Users\scott\.vscode\extensions\angular.ng-template-0.1000.7\server\node_modules\@angular\language-service\bundles\language-service.js (resolved to c:/Users/scott/.vscode/extensions/angular.ng-template-0.1000.7/server/node_modules/@angular/language-service/bundles/language-service.js/node_modules)
Info 12   [11:32:56.58] Plugin validation succeded
Info 13   [11:32:56.617] Starting updateGraphWorker: Project: c:/Users/scott/projectsAngular/psykdesk-admin/tsconfig.json
**Err 14    [11:33:8.56] Analyzing NgModules failed. TypeError: Cannot read property 'name' of undefined**
Info 15   [11:33:8.56] Finishing updateGraphWorker: Project: c:/Users/scott/projectsAngular/psykdesk-admin/tsconfig.json Version: 1 structureChanged: true Elapsed: 11439ms
Info 16   [11:33:8.56] Project 'c:/Users/scott/projectsAngular/psykdesk-admin/tsconfig.json' (Configured)
Info 17   [11:33:8.56] 	Files (1222)

nglangsvc.log attached below

[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/5063882/nglangsvc.log)

Any ideas as to where to look next?
Thanks,

**Comment by singulli1** [comment]
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/5063877/nglangsvc.log)

**Comment by alexcalbajos** [comment]
I am getting the same error even though ng serve and ng build produce no errors. I managed to isolate the issue to a specific NgModule from the app but I can't understand what's producing this.

I also opened my project in WebStorm and the angular language service is working fine there.

I can provide logs if needed as well.

**Comment by alexcalbajos** [comment]
@singulli1 I think it might be related to #925 

I had the same symptoms as you and I was able to fix it that way. It still remains a mystery to me why that package stops the language service or the extension.

**Comment by Dzivo** [comment]
I have the same issue with my library.
Library build works fine and library projects runs but i have error in VS code showing 

> drag-and-drop-area' is not a known element

**Comment by epaitz** [comment]
I had the same issue and posted details many months ago. If you restart the Angular Language Service the error goes away but the error will reappear as soon as you rebuild which is extremely annoying. 

[Not a known element when referencing an Angular Component from a library project using npm link](https://github.com/angular/vscode-ng-language-service/issues/735)

I was told that it would eventually be resolved but its been about 6 months since my post and I am still seeing this issue.

I think there are many people in the community that would love to have this fixed. 

Please consider getting this fixed before the end of 2020.

**Comment by ayazhafiz** [comment]
This will be fixed by the upcoming Ivy-native Language Service, information on which can be found [here](https://github.com/angular/vscode-ng-language-service/issues/335#issuecomment-693545000), but not before then due to the inherent limitations of the current implementation of the language service. We realize that this has been a long time coming and appreciate your patience as we try to polish it up.

**Comment by kyliau** [comment]
This has been fixed by the new Ivy-native language service, released in [v11.1.0](https://github.com/angular/vscode-ng-language-service/releases/tag/v11.1.0).
It's an opt-in feature for now, please give it a try and let us know if you have any feedback.
For the best editor experience, please make sure your project has [`strictTemplates`](https://angular.io/guide/angular-compiler-options#stricttemplates) enabled in `angularCompilerOptions`.
In case you run into similar bug, please file a new issue. I'll close this for now.
