### ISSUE TITLE
Paths with "#" not resolved correctly

### ISSUE THREAD

**Issue by payambordbar** [angular/vscode-ng-language-service#892]
If there is a # in the path of a project, the extension will not work
for example:
F:\Source\C#\My Project\client

But if we remove #, the Angular language service will work properly

**Comment by ayazhafiz** [comment]
This is a bug in Angular's URL resolver:

https://github.com/angular/angular/blob/0aa53cdd6081177ddf384eed511e10e7db458c33/packages/compiler/src/url_resolver.ts#L55-L71

As a simple reproduction, `resolve('a/b/c#/d.ts', './d.html')` will give back `a/b/d.ts` but should give back `a/b/c#/d.html`.

This manifests itself in the language service because when initializing a project, TypeScript calls the Angular language service plugin for external files. We return external files as the set of external templates in the project, which we compute using the url resolver:

https://github.com/angular/angular/blob/0aa53cdd6081177ddf384eed511e10e7db458c33/packages/language-service/src/typescript_host.ts#L194-L206
