### ISSUE TITLE
Make underlining of private members in template optional

### ISSUE THREAD

**Issue by cortopy** [angular/vscode-ng-language-service#95]
Currently private properties in the component get underlined in the template.

However, it can be argued that templates are within the component's scope as they're added via decorator in the component's metadata. So my use of private property is reserved for methods which shouldn't be accessed by other components.

Would it be possible to have an option to ignore private methods warnings in template?

**Comment by hccampos** [comment]
Angular treats a template as a separate entity that uses an instance of the component, so no private properties can be accessed. If you try to compile AoT, it will break.

I don't agree with that architectural decision, but it has been made and we have to live with it. Because of that, I would advise against adding an option to disable the private property checks.

**Comment by cortopy** [comment]
I've always used private properties in templates and never had an issue, whether that's AOT or JIT compilation. The only issue I've had is tslint saying private property is not being used. Disabling that rule for every project just gets rid of the message. 

I only started using this extension this week and my thought was whether the same thing could be done. I don't know where errors are obtained from so not sure if it was possible.

**Comment by chuckjaz** [comment]
@cortopy The language service will emit these errors because they will be errors during AOT. Eventually you will need to resolve these.

We have plans to support access to private and protected members in AOT but that will not land until at least 6.0 (spring of next year).
