### ISSUE TITLE
in the html page,some code's color is wrong

### ISSUE THREAD

**Issue by EchoBeTaken** [angular/vscode-ng-language-service#957]
![color error](https://user-images.githubusercontent.com/19503850/98214219-2f50d180-1f81-11eb-85ab-fb47fa2903a3.jpg)
in line 168, below the line,the code's color becomes green, if i delete the 'click',the color will become right.
but above , there also are 'click's,just begin from this line and this 'click', it looks like strange .

**Comment by ayazhafiz** [comment]
Can you provide us with some more information:

- What version of the extension are you using?
- Are you using any other extensions along with this one?
- What is a minimal reproduction of this issue? If you cannot create one, can you share this entire file with us, or at least the contents of the entire lines where this problem is happening? Please provide this as text rather than an image.

Thank you.

**Comment by EchoBeTaken** [comment]
[setting.component.zip](https://github.com/angular/vscode-ng-language-service/files/5498280/setting.component.zip)
0. this is the html file
1. version is 0.1001.1
2. when i just enable this extension, the question is also appear

**Comment by ayazhafiz** [comment]
Thank you so much for the information. The linked pull request fixes this issue.
